/**
 * Central image manifest. Files live in /public/images as optimized WebP
 * (generated by scripts/optimize-images.mjs). Editorial photos ship in two
 * widths (`-sm` / `-lg`); portraits in `-450` / `-900`.
 */

export interface EditorialImage {
  sm: string;
  lg: string;
  alt: string;
}

export interface PortraitImage {
  sm: string;
  lg: string;
}

const ed = (slug: string, alt: string): EditorialImage => ({
  sm: `/images/${slug}-sm.webp`,
  lg: `/images/${slug}-lg.webp`,
  alt,
});

export const photos = {
  clinicRoom: ed("clinic-room", "Heller Behandlungsraum im MOTIO Health Lab"),
  therapyNeck: ed("therapy-neck", "Physiotherapeut behandelt Nacken und Schulter"),
  mobilityLegRaise: ed("mobility-leg-raise", "Beweglichkeitstest des Beins auf der Behandlungsliege"),
  assessmentStanding: ed("assessment-standing", "Therapeut analysiert die Haltung im Stehen"),
  mobilityHamstring: ed("mobility-hamstring", "Dehnung der hinteren Beinmuskulatur"),
  postureBack: ed("posture-back", "Haltungsanalyse der Wirbelsäule"),
  athleticSwing: ed("athletic-swing", "Athletische Beweglichkeitsübung im Stehen"),
  therapyKnee: ed("therapy-knee", "Manuelle Therapie am Knie"),
  trainingCore: ed("training-core", "Rumpftraining auf der Matte im Trainingsbereich"),
  therapyFoot: ed("therapy-foot", "Manuelle Behandlung von Fuß und Sprunggelenk"),
  mobilityOverhead: ed("mobility-overhead", "Mobilisation der Schulter über Kopf"),
  therapyShoulder: ed("therapy-shoulder", "Behandlung von Nacken und Schulter"),
  osteoNeck: ed("osteo-neck", "Osteopathische Behandlung im Nackenbereich"),
  handsCare: ed("hands-care", "Therapeutische Hände halten die Hand einer Patientin"),
  wristAssessment: ed("wrist-assessment", "Untersuchung von Handgelenk und Arm"),
  resistanceBand: ed("resistance-band", "Training mit dem Widerstandsband"),
  shoulderClose: ed("shoulder-close", "Nahaufnahme einer Schulterbehandlung"),
  kneeTreatment: ed("knee-treatment", "Manuelle Therapie am Knie auf der Liege"),
} as const;

export const portraitBySlug: Record<string, PortraitImage> = {
  "matteo-brandt": { sm: "/images/matteo-brandt-450.webp", lg: "/images/matteo-brandt-900.webp" },
  "sophia-lindner": { sm: "/images/sophia-lindner-450.webp", lg: "/images/sophia-lindner-900.webp" },
  "julia-ahrens": { sm: "/images/julia-ahrens-450.webp", lg: "/images/julia-ahrens-900.webp" },
  "tom-winkler": { sm: "/images/tom-winkler-450.webp", lg: "/images/tom-winkler-900.webp" },
  "elena-rossi": { sm: "/images/elena-rossi-450.webp", lg: "/images/elena-rossi-900.webp" },
};

export function slugFromName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}
